In [1]:
import pandas as pd
import numpy as np
import datetime
import re
import os

In [4]:
DTYPE={

    0:  str,      # RecNum                ## str in original schema
    1:  int,      # FiscalYear            ## str in original schema
    2:  str,      # entity name
    3:  str,      # Fund1
    4:  str,      # Fund2
    5:  str,      # Fund3
    6:  str,      # Fund4
    7:  str,      # Org1
    8:  str,      # Org2
    9:  str,      # Org3
    10: str,      # Org4
    11: str,      # Org5
    12: str,      # Org6
    13: str,      # Org7
    14: str,      # Org8
    15: str,      # Org9
    16: str,      # Org10
    17: str,      # Trans Type
    18: str,      # Cat1                  ## conditional
    19: str,      # Cat2
    20: str,      # Cat3
    21: str,      # Cat4
    22: str,      # Cat5
    23: str,      # Cat6
    24: str,      # Cat7
    25: str,      # PCV name              ## conditional
    26: str,      # DBA
    27: str,      # vndr Id
#   28: str,      # posting date
    29: str,      # Trans Desc
    30: str,      # transaction ID
    31: str,      # ref id
    32: str,      # contact name
    33: str,      # contract num
    34: str,      # title
    35: np.float, # hourly rate           ## float take NAs
    36: str,      # gender
    37: np.float, # amount
    38: str,      # masked
    39: str,      # UCA
            }




df=pd.read_csv("H:/Transparency/Transparent Utah 3.0/Raw Batches/rawBatch/_data_56125.txt",
               header=None, sep='|',
               thousands=',',
               low_memory=False,
               parse_dates=[28],
               encoding='cp1252',
               dtype=DTYPE
              )




info = [
    'RcNm', 'FsYr', 'Name',
    'Fnd1', 'Fnd2', 'Fnd3', 'Fnd4',
    'Org1', 'Org2', 'Org3', 'Org4', 'Org5', 'Org6', 'Org7', 'Org8', 'Org9', 'OrgX',
    'Type',
    'Cat1', 'Cat2', 'Cat3', 'Cat4', 'Cat5', 'Cat6', 'Cat7',
    'Vndr', 'VDBA', 'VIDC', 'Pdat', 'Desc', 'TID', 'TRef', 'Cnam', 'Cnum', 'PTit', 'Hrat', 'Gend', 'Amnt', 'PI',
]
uca = [ 'UCA', ]
psd = [
    'Prg1', 'Prg2', 'Prg3', 'Prg4', 'Prg5', 'Prg6', 'Prg7',
    'Fnc1', 'Fnc2', 'Fnc3', 'Fnc4', 'Fnc5', 'Fnc6', 'Fnc7',
]
COLLEN = len(df.columns)

if COLLEN == 40:
    info += uca
elif COLLEN == 54:
    info += uca + psd
    PSD = True

elif COLLEN ==41:
    info += uca + ['EMPTY']

elif COLLEN ==55:
    info += uca + psd + ['EMPTY']
    PSD = True
    
    
df.rename(inplace=True, columns=lambda x: info[x])

ValueError: could not convert string to float: